FIRST_SET = {
    "<program>": ["piece", "sip", "flag", "chars", "table", "id", "prepare", "start"],
    "<global_decl>": ["piece", "sip", "flag", "chars", "table", "id", "λ"],
    "<decl_data_type>": ["piece", "sip", "flag", "chars"],
    "<decl_type>": ["of", "["],
    "<ingredient_id>": ["id"],
    "<ingredient_init>": ["=", "λ"],
    "<ingredient_id_tail>": [",", "λ"],
    "<expr>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
               "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
               "remove", "reverse", "search", "size", "sort", "sqrt", "take",
               "tochars", "topiece", "tosip"],
    "<or_expr>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                  "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                  "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                  "tochars", "topiece", "tosip"],
    "<and_expr>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                   "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                   "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                   "tochars", "topiece", "tosip"],
    "<or_tail>": ["or", "λ"],
    "<eq_expr>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                  "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                  "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                  "tochars", "topiece", "tosip"],
    "<and_tail>": ["and", "λ"],
    "<rel_expr>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                   "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                   "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                   "tochars", "topiece", "tosip"],
    "<eq_tail>": ["==", "!=", "λ"],
    "<add_expr>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                   "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                   "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                   "tochars", "topiece", "tosip"],
    "<rel_tail>": [">", "<", ">=", "<=", "λ"],
    "<mult_expr>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                    "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                    "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                    "tochars", "topiece", "tosip"],
    "<add_tail>": ["+", "-", "λ"],
    "<unary_expr>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                     "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                     "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                     "tochars", "topiece", "tosip"],
    "<mult_tail>": ["*", "/", "%", "λ"],
    "<primary_val>": ["(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                      "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                      "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                      "tochars", "topiece", "tosip"],
    "<id_tail>": ["(", "[", ":", "λ"],
    "<call_tailopt>": ["(", "λ"],
    "<accessor_tail>": ["[", ":", "λ"],
    "<array_accessor>": ["["],
    "<table_accessor>": [":"],
    "<flavor>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                  "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                  "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                  "tochars", "topiece", "tosip", "[", "λ"],
    "<value>": ["not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit", "id",
                "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                "tochars", "topiece", "tosip", "["],
    "<notation_val>": ["piece_lit", "sip_lit", "flag_lit", "chars_lit",
                       "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                       "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                       "tochars", "topiece", "tosip", "[", "id"],
    "<element_value_tail>": [",", "λ"],
    "<notation_val1>": ["piece_lit", "sip_lit", "flag_lit", "chars_lit",
                         "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                         "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                         "tochars", "topiece", "tosip", "id"],
    "<id_notation_tail>": ["(", "[", ":", ",", "λ", "="],
    "<assignment_st_eq>": ["="],
    "<field_assignments>": ["id", "λ"],
    "<flavor_tail>": [",", "λ"],
    "<built-in_rec_call>": ["append", "bill", "copy", "cut", "fact", "matches",
                            "pow", "rand", "remove", "reverse", "search", "size", "sort",
                            "sqrt", "take", "tochars", "topiece", "tosip"],
    "<tail1>": ["("],
    "<built-in_rec>": ["append", "bill", "copy", "cut", "fact", "matches",
                       "pow", "rand", "remove", "reverse", "search", "size", "sort",
                       "sqrt", "take", "tochars", "topiece", "tosip"],
    "<call_tail>": ["("],
    "<dimensions>": ["["],
    "<dimensions_tail>": ["[", "λ"],
    "<array_declare>": ["id"],
    "<array_table_init>": ["=", "λ"],
    "<array_declare_tail>": [",", "λ"],
    "<table_prototype>": ["table"],
    "<required_decl>": ["piece", "sip", "flag", "chars", "id"],
    "<decl_head>": ["piece", "sip", "flag", "chars", "id"],
    "<data_types_dims>": ["piece", "sip", "flag", "chars", "id"],
    "<required_decl_tail>": ["piece", "sip", "flag", "chars", "id", "λ"],
    "<table_decl>": ["[", "of"],
    "<table_declare>": ["id"],
    "<table_declare_tail>": [",", "λ"],
    "<recipe_decl>": ["prepare", "λ"],
    "<spice>": ["piece", "sip", "flag", "chars", "id", "λ"],
    "<spice_tail>": [",", "λ"],
    "<platter>": ["{"],
    "<local_decl>": ["piece", "sip", "flag", "chars", "id", "λ"],
    "<statements>": ["id", "append", "bill", "copy", "cut", "fact", "matches", "pow",
                     "rand", "remove", "reverse", "search", "size", "sort", "sqrt",
                     "take", "tochars", "topiece", "tosip", "check", "menu", "pass",
                     "repeat", "order", "next", "stop", "serve", "λ"],
    "<local_id_tail>": ["of", "[", ":", "=", "+=", "-=", "*=", "/=", "%=", "("],
    "<]_tail>": ["]", "not", "(", "piece_lit", "sip_lit", "flag_lit", "chars_lit",
                 "id", "append", "bill", "copy", "cut", "fact", "matches", "pow", "rand",
                 "remove", "reverse", "search", "size", "sort", "sqrt", "take",
                 "tochars", "topiece", "tosip"],
    "<id_statements>": ["id"],
    "<id_statements_ext>": ["(", "[", ":", "=", "+=", "-=", "*=", "/=", "%="],
    "<assignment_st>": ["[", ":", "=", "+=", "-=", "*=", "/=", "%="],
    "<assignment_op>": ["=", "+=", "-=", "*=", "/=", "%="],
    "<conditional_st>": ["check", "menu"],
    "<cond_check>": ["check"],
    "<alt_clause>": ["alt", "λ"],
    "<instead_clause>": ["instead", "λ"],
    "<cond_menu>": ["menu"],
    "<menu_platter>": ["{"],
    "<choice_clause>": ["choice", "λ"],
    "<usual_clause>": ["usual", "λ"],
    "<looping_st>": ["pass", "repeat", "order"],
    "<loop_pass>": ["pass"],
    "<loop_repeat>": ["repeat"],
    "<loop_order>": ["order"],
    "<jump_st>": ["next", "stop", "serve"],
    "<jump_next>": ["next"],
    "<jump_stop>": ["stop"],
    "<jump_serve>": ["serve"]
}
