TOKEN_MAP = {
  # Data Types
  "CHARS": "chars",
  "FLAG": "flag",
  "PIECE": "piece",
  "SIP": "sip",
  "TABLE": "table",
  # Logical Operators
  "AND": "and",
  "NOT": "not",
  "OR": "or",
  # Conditional Statements
  "ALT": "alt",
  "CHECK": "check",
  "CHOICE": "choice",
  "INSTEAD": "instead",
  "MENU": "menu",
  "USUAL": "usual",
  # Looping Statements
  "ORDER": "order",
  "PASS": "pass",
  "REPEAT": "repeat",
  # Jump Statements
  "NEXT": "next",
  "STOP": "stop",
  "SERVE": "serve",
  # Built-in Recipes
  "APPEND": "append",
  "BILL": "bill",
  "COPY": "copy",
  "CUT": "cut",
  "FACT": "fact",
  "MATcHES": "matches",
  "POW": "pow",
  "RAND": "rand",
  "REMOVE": "remove",
  "REVERSE": "reverse",
  "SEARCH": "search",
  "SIZE": "size",
  "SORT": "sort",
  "SQRT": "sqrt",
  "TAKE": "take",
  "TOCHARS": "tochars",
  "TOPIECE": "topiece",
  "TOSIP": "tosip",
  # Others
  "DOWN": "down",
  "OF": "of",
  "PREPARE": "prepare",
  "START": "start",
  "UP": "up",
  # Arithmetic Operators
  "PLUS": "+",
  "SUB": "-",
  "MUL": "*",
  "DIV": "/",
  "MOD": "%",
  # Relational Operators
  "G_THAN": ">",
  "L_THAN": "<",
  "2EQUAL": "==",
  "LEQUAL": "<=",
  "GEQUAL": ">=",
  "NEQUAL": "!=",
  # Assignment Operators
  "EQUAL": "=",
  "PLUSEQ": "+=",
  "SUBEQ": "-=",
  "MULEQUAL": "*=",
  "DIVEQUAL": "/=",
  "MODEQUAL": "%=",
  # Other Symbols
  "LBRACE": "{",
  "RBRACE": "}",
  "LPAREN": "(",
  "RPAREN": ")",
  "LSQB": "[",
  "RSQB": "]",
  "COMMA": ",",
  "SEMICOLON": ";",
  "COLON": ":",
  "NEWLINE": "newline",
  "TAB": "tab",
  "SPACE": "space",
  # Others
  "PIECE_LIT": "piece_lit",
  "SIP_LIT": "sip_lit",
  "CHARS_LIT": "chars_lit",
  "ID": "id",
  "COMMENT_SINGLE": "comment_single",
  "COMMENT_MULTI": "comment_multi"
}